import * as React from "react";
import type { Metadata } from "next";
import { TermsClient } from "@/app/(storefront)/pages/terms-of-sale/terms-client";

export const metadata: Metadata = {
  title: "Product Data Information | Nothing Official Pakistan",
  description:
    "Information pursuant to the EU Data Act on product data generated by Nothing smartphones, earbuds, CMF watches, and the Nothing X app.",
  alternates: {
    canonical: "https://www.nothingcmf.pk/pages/product-data-information",
  },
  openGraph: {
    title: "Product Data Information | Nothing Official Pakistan",
    description:
      "Product data information for smartphones, earbuds, watches and the Nothing X app.",
    url: "https://www.nothingcmf.pk/pages/product-data-information",
  },
};

export default function ProductDataInformationPage() {
  return <TermsClient initialPolicy="product-data-information" />;
}
